services:
  evocelot-file-service:
    container_name: evocelot-file-service
    image: icellmobilsoft/wildfly-mp-full-mariadb-jdbc:3.0.0
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
    volumes:
      - '../config/wildfly/file.properties:/home/icellmobilsoft/config/wildfly.properties'
      - /c/file-service:/files # Stores the files into the /c/file-service folder
    environment:
      COFFEE_APP_PROJECTSTAGE: Dev
      HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
      MARIADB_DS_CONNECTION_URL: jdbc:mariadb://evocelot-file-service-mariadb:3306/file
      MARIADB_DS_USERNAME: root
      MARIADB_DS_PASSWORD: admin
      OTEL_SERVICE_NAME: evocelot-file-service
      OTEL_SDK_DISABLED: true
      OPENTELEMETRY_SAMPLER_TYPE: ratio
      OPENTELEMETRY_SAMPLER_RATIO: 1
      OPENTELEMETRY_EXPORTER_ENDPOINT: http://evocelot-jaeger:14250
      OPENTELEMETRY_EXPORTER_TYPE: jaeger
      LOGSTASH_ENABLED: false
      LOGSTASH_HOST: evocelot-logstash
      LOGSTASH_PORT: 9300
      MICROMETER_ENDPOINT: http://evocelot-opentelemetry-collector:4318/v1/metrics
      DEBUG: true
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks:
  default:
    name: evocelot-network
